In [8]:
import numpy as np

class CPCA(object):
    def __init__(self,X,K):
        self.X = X
        self.K = K
        self.centrX = []
        self.C = []
        self.U = []
        self.Z = []
        
        self.centrX = self._centralized()
        self.C = self._cov()
        self.U = self._U()
        self.Z = self._Z()
        
    #矩阵中心化
    def _centralized(self):
        print('样本矩阵X:\n',self.X)
        centrX = []
        mean = np.array([np.mean(attr) for attr in self.X.T])
        print('样本的特征均值:\n',mean)
        centrX = self.X-mean
        print('样本矩阵X的中心化centterX:\n',centrX)
        return centrX
    
    #求协方差矩阵
    def _cov(self):
        ns = np.shape(self.centrX)[0]
        C = np.dot(self.centrX.T,self.centrX)/(ns - 1)
        print('样本矩阵X的协方差矩阵C:\n',C)
        return C
    
    def _U(self):
        a,b = np.linalg.eig(self.C)
        print('样本集的协方差矩阵C的特征值:\n',a)
        print('样本集的协方差矩阵C的特征向量:\n',b)
        ind = np.argsort(-1*a)
        UT = [b[:,ind[i]] for i in range(self.K) ]
        U = np.transpose(UT)
        print('%d阶降维转换矩阵U:\n'%self.K,U)
        #%d 和 \n 用法有什么区别？
        return U
    
    def _Z(self):
        Z = np.dot(self.X,self.U)
        print('X shape', np.shape(self.X))
        print('U shape', np.shape(self.U))
        print('Z shape', np.shape(Z))
        print('样本矩阵X的降维矩阵Z:\n',Z)
        return Z
    
if __name__=='__main__':
    
        X = np.array([[10, 15, 29],
                        [15, 46, 13],
                        [23, 21, 30],
                        [11, 9, 35],
                        [42, 45, 11],
                        [9, 48, 5],
                        [11, 21, 14],
                        [8, 5, 15],
                        [11, 12, 21],
                        [21, 20, 25]])
        K = np.shape(X)[1]-1
        print('样本集（10行3列，10个样例，每个样例3个特征）：\n',X)
        pca = CPCA(X,K)
       
        

样本集（10行3列，10个样例，每个样例3个特征）：
 [[10 15 29]
 [15 46 13]
 [23 21 30]
 [11  9 35]
 [42 45 11]
 [ 9 48  5]
 [11 21 14]
 [ 8  5 15]
 [11 12 21]
 [21 20 25]]
样本矩阵X:
 [[10 15 29]
 [15 46 13]
 [23 21 30]
 [11  9 35]
 [42 45 11]
 [ 9 48  5]
 [11 21 14]
 [ 8  5 15]
 [11 12 21]
 [21 20 25]]
样本的特征均值:
 [16.1 24.2 19.8]
样本矩阵X的中心化centterX:
 [[ -6.1  -9.2   9.2]
 [ -1.1  21.8  -6.8]
 [  6.9  -3.2  10.2]
 [ -5.1 -15.2  15.2]
 [ 25.9  20.8  -8.8]
 [ -7.1  23.8 -14.8]
 [ -5.1  -3.2  -5.8]
 [ -8.1 -19.2  -4.8]
 [ -5.1 -12.2   1.2]
 [  4.9  -4.2   5.2]]
样本矩阵X的协方差矩阵C:
 [[ 108.32222222   74.53333333  -10.08888889]
 [  74.53333333  260.62222222 -106.4       ]
 [ -10.08888889 -106.4          94.17777778]]
样本集的协方差矩阵C的特征值:
 [335.15738485  95.32771231  32.63712506]
样本集的协方差矩阵C的特征向量:
 [[-0.30253213 -0.87499307 -0.37797014]
 [-0.86718533  0.08811216  0.49012839]
 [ 0.39555518 -0.47604975  0.78543792]]
2阶降维转换矩阵U:
 [[-0.30253213 -0.87499307]
 [-0.86718533  0.08811216]
 [ 0.39555518 -0.47604975]]
X shape (10, 3)
U shape (

In [ ]:
sds