In [5]:
import cv2
import numpy as np

img = cv2.imread("photo1.jpg")
result = img.copy()

src = np.float32([[207, 151], [517, 285], [17, 601], [343, 731]])
dst = np.float32([[0, 0], [337, 0], [0, 488], [337, 488]])

m = cv2.getPerspectiveTransform(src, dst) #透视变换矩阵
print('透视变换矩阵:\n', m)

result = cv2.warpPerspective(result, m, (377, 488)) #输入图像，透视变换矩阵和预估尺寸

cv2.imshow('original image', img)
cv2.imshow('new image', result)

cv2.waitKey(0)


透视变换矩阵:
 [[ 8.92263779e-01  3.76733596e-01 -2.41585375e+02]
 [-4.08140258e-01  9.44205073e-01 -5.80899328e+01]
 [-8.53836442e-05  5.16464182e-05  1.00000000e+00]]


-1